// <auto-generated />
using System;
using BeBlueApi.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeBlueApi.Infra.Data.Migrations
{
    [DbContext(typeof(BeblueDbContext))]
    partial class BeblueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeBlueApi.Domain.Models.Cashback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdGender");

                    b.Property<decimal>("Percent");

                    b.Property<int>("WeekDay");

                    b.HasKey("Id");

                    b.HasIndex("IdGender");

                    b.ToTable("Cashback");
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.DiscMusic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumGroup");

                    b.Property<string>("ArtistName");

                    b.Property<Guid>("IdGender");

                    b.Property<string>("IdSpotify");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("IdGender");

                    b.ToTable("DiscMusic");
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.MusicGender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("MusicGender");
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.Sales", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("SalesDate");

                    b.Property<decimal>("TotalAmount");

                    b.Property<decimal>("TotalCashback");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.SalesLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cashback");

                    b.Property<string>("DiscName")
                        .HasMaxLength(250);

                    b.Property<Guid>("IdItem");

                    b.Property<Guid>("IdSales");

                    b.Property<decimal>("PriceUnit");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("SalesPrice");

                    b.HasKey("Id");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdSales");

                    b.ToTable("SalesLine");
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.Cashback", b =>
                {
                    b.HasOne("BeBlueApi.Domain.Models.MusicGender", "MusicGender")
                        .WithMany("Cashbacks")
                        .HasForeignKey("IdGender")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.DiscMusic", b =>
                {
                    b.HasOne("BeBlueApi.Domain.Models.MusicGender", "MusicGender")
                        .WithMany("DiscMusics")
                        .HasForeignKey("IdGender")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeBlueApi.Domain.Models.SalesLine", b =>
                {
                    b.HasOne("BeBlueApi.Domain.Models.DiscMusic", "DiscMusic")
                        .WithMany("SalesLines")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeBlueApi.Domain.Models.Sales", "Sales")
                        .WithMany("Lines")
                        .HasForeignKey("IdSales")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
