version: '3'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
        SA_PASSWORD: "MyPassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network
  core:
    build:
      context: .
      dockerfile: .
    networks:
      - sqlserver-network
    depends_on:
      - sqlserver
      
networks: 
  sqlserver-network:
    driver: bridge